#!/bin/bash
computer_type="$1"
ip="$2"
password="$3"
username="shutdown"
timebefore="1"

echo "Turning off computer with IP Address: $ip"
if  [[ $computer_type == "1" ]]
	then
		echo "Type:Windows"
		echo "Sending windows requests"
		echo net rpc shutdown -h -I $ip -C "Remote Shutdown" -t $timebefore -U "$username%$password";
		net rpc shutdown -h -I $ip -C "Remote Shutdown" -t $timebefore -U "$username%$password";
fi

if [[ $computer_type == "2" ]]
	then
		echo "Type:Linux"
		echo "Sending ssh shutdown requests on $ip"
		sshpass -p $password ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no shutdown@$ip
fi
